/* Generated by native/shaders/generate.py - do not edit. */
#ifndef AE3D_VK_UNIFORMS_H
#define AE3D_VK_UNIFORMS_H

#include <string.h>

#define AE3D_VK_SCENE_SIZE 4720

/* std140 layout, offsets computed from the same declarations the shader
   block is generated from, so the two cannot disagree. */
typedef struct {
    unsigned char bytes[4720];
} ae3d_vk_scene;

#define AE3D_VK_OFF_ISINSTANCED 320
#define AE3D_VK_OFF_USEINSTANCECOLOR 324
#define AE3D_VK_OFF_MODEL 336
#define AE3D_VK_OFF_VIEWPROJECTION 400
#define AE3D_VK_OFF_LIGHTSPACEMATRIX 464
#define AE3D_VK_OFF_ISSKINNED 528
#define AE3D_VK_OFF_BONES 544
#define AE3D_VK_OFF_LIGHTCOUNT 3616
#define AE3D_VK_OFF_VIEWPOS 3632
#define AE3D_VK_OFF_VIEWDISTANCE 3644
#define AE3D_VK_OFF_DIFFUSECOLOR 3648
#define AE3D_VK_OFF_SPECULARCOLOR 3664
#define AE3D_VK_OFF_METALLIC 3676
#define AE3D_VK_OFF_ROUGHNESS 3680
#define AE3D_VK_OFF_EXPOSURE 3684
#define AE3D_VK_OFF_MATERIALALPHA 3688
#define AE3D_VK_OFF_REFLECTIVITY 3692
#define AE3D_VK_OFF_HASNORMALMAP 3696
#define AE3D_VK_OFF_NORMALSTRENGTH 3700
#define AE3D_VK_OFF_OCCLUSIONSTRENGTH 3704
#define AE3D_VK_OFF_ENABLECLEARCOAT 3708
#define AE3D_VK_OFF_CLEARCOATROUGHNESS 3712
#define AE3D_VK_OFF_CLEARCOATINTENSITY 3716
#define AE3D_VK_OFF_ENABLESHEEN 3720
#define AE3D_VK_OFF_SHEENCOLOR 3728
#define AE3D_VK_OFF_SHEENROUGHNESS 3740
#define AE3D_VK_OFF_ENABLETRANSMISSION 3744
#define AE3D_VK_OFF_TRANSMISSIONFACTOR 3748
#define AE3D_VK_OFF_ENABLEMULTIPLESCATTERING 3752
#define AE3D_VK_OFF_ENABLEENERGYCONSERVATION 3756
#define AE3D_VK_OFF_ENABLEIMAGEBASEDLIGHTING 3760
#define AE3D_VK_OFF_IBLINTENSITY 3764
#define AE3D_VK_OFF_ENABLEVOLUMETRICLIGHTING 3768
#define AE3D_VK_OFF_VOLUMETRICINTENSITY 3772
#define AE3D_VK_OFF_VOLUMETRICSTEPS 3776
#define AE3D_VK_OFF_VOLUMETRICSCATTERING 3780
#define AE3D_VK_OFF_ENABLESSAO 3784
#define AE3D_VK_OFF_SSAOINTENSITY 3788
#define AE3D_VK_OFF_SSAORADIUS 3792
#define AE3D_VK_OFF_SSAOBIAS 3796
#define AE3D_VK_OFF_SSAOSAMPLECOUNT 3800
#define AE3D_VK_OFF_ENABLEGLOBALILLUMINATION 3804
#define AE3D_VK_OFF_GIINTENSITY 3808
#define AE3D_VK_OFF_GIBOUNCES 3812
#define AE3D_VK_OFF_ENABLEBLOOM 3816
#define AE3D_VK_OFF_BLOOMTHRESHOLD 3820
#define AE3D_VK_OFF_BLOOMINTENSITY 3824
#define AE3D_VK_OFF_ENABLEFOG 3828
#define AE3D_VK_OFF_FOGSTART 3832
#define AE3D_VK_OFF_FOGEND 3836
#define AE3D_VK_OFF_FOGCOLOR 3840
#define AE3D_VK_OFF_FOGINTENSITY 3852
#define AE3D_VK_OFF_ENABLESHADOWS 3856
#define AE3D_VK_OFF_HASSHADOWMAP 3860
#define AE3D_VK_OFF_SHADOWINTENSITY 3864
#define AE3D_VK_OFF_SHADOWSOFTNESS 3868
#define AE3D_VK_OFF_SHADOWDIRECTION 3872
#define AE3D_VK_OFF_SHADOWTEXELWORLD 3884
#define AE3D_VK_OFF_ENABLEPERLINNOISE 3888
#define AE3D_VK_OFF_NOISESCALE 3892
#define AE3D_VK_OFF_NOISEOCTAVES 3896
#define AE3D_VK_OFF_NOISEINTENSITY 3900
#define AE3D_VK_OFF_ENABLECAUSTICS 3904
#define AE3D_VK_OFF_CAUSTICSINTENSITY 3908
#define AE3D_VK_OFF_CAUSTICSSCALE 3912
#define AE3D_VK_OFF_CAUSTICSSPEED 3916
#define AE3D_VK_OFF_CAUSTICSWATERLEVEL 3920
#define AE3D_VK_OFF_CAUSTICSDEPTH 3924
#define AE3D_VK_OFF_CAUSTICSTIME 3928
#define AE3D_VK_OFF_PROJECTION 3936
#define AE3D_VK_OFF_VIEW 4000
#define AE3D_VK_OFF_TEXELSIZE 4064
#define AE3D_VK_OFF_EDGETHRESHOLD 4072
#define AE3D_VK_OFF_EDGETHRESHOLDMIN 4076
#define AE3D_VK_OFF_SUBPIXELQUALITY 4080
#define AE3D_VK_OFF_INVVIEWPROJECTION 4096
#define AE3D_VK_OFF_SSRROADHEIGHT 4160
#define AE3D_VK_OFF_SSRSTRENGTH 4164
#define AE3D_VK_OFF_TIME 4168
#define AE3D_VK_OFF_WAVESPEEDMULTIPLIER 4172
#define AE3D_VK_OFF_WAVEHEIGHTMULTIPLIER 4176
#define AE3D_VK_OFF_WAVERANDOMNESS 4180
#define AE3D_VK_OFF_WAVEDIRECTIONS 4192
#define AE3D_VK_OFF_WAVEAMPLITUDES 4256
#define AE3D_VK_OFF_WAVEFREQUENCIES 4320
#define AE3D_VK_OFF_WAVESPEEDS 4384
#define AE3D_VK_OFF_WAVEPHASES 4448
#define AE3D_VK_OFF_WAVESTEEPNESS 4512
#define AE3D_VK_OFF_LIGHTPOS 4576
#define AE3D_VK_OFF_LIGHTDIRECTION 4592
#define AE3D_VK_OFF_LIGHTCOLOR 4608
#define AE3D_VK_OFF_LIGHTINTENSITY 4620
#define AE3D_VK_OFF_WATERBASECOLOR 4624
#define AE3D_VK_OFF_WATEROPACITY 4636
#define AE3D_VK_OFF_ENABLEFOAM 4640
#define AE3D_VK_OFF_FOAMINTENSITY 4644
#define AE3D_VK_OFF_WATERPLANEHEIGHT 4648
#define AE3D_VK_OFF_WATERLEVEL 4652
#define AE3D_VK_OFF_SKYCOLOR 4656
#define AE3D_VK_OFF_HORIZONCOLOR 4672
#define AE3D_VK_OFF_ENABLEWATERREFLECTION 4684
#define AE3D_VK_OFF_WATERREFLECTIONINTENSITY 4688
#define AE3D_VK_OFF_HASSKYTEXTURE 4692
#define AE3D_VK_OFF_ENABLEWATERDISTORTION 4696
#define AE3D_VK_OFF_WATERDISTORTIONINTENSITY 4700
#define AE3D_VK_OFF_ENABLEWATERNORMALMAPPING 4704
#define AE3D_VK_OFF_WATERNORMALINTENSITY 4708
#define AE3D_VK_OFF_POSEBANKFRAMES 4712

#define AE3D_VK_MAX_LIGHTS 4
#define AE3D_VK_LIGHT_STRIDE 80
#define AE3D_VK_LIGHT_POSITION 0
#define AE3D_VK_LIGHT_COLOR 16
#define AE3D_VK_LIGHT_INTENSITY 28
#define AE3D_VK_LIGHT_AMBIENTSTRENGTH 32
#define AE3D_VK_LIGHT_TEMPERATURE 36
#define AE3D_VK_LIGHT_ISDIRECTIONAL 40
#define AE3D_VK_LIGHT_DIRECTION 48
#define AE3D_VK_LIGHT_CONSTANTATTEN 60
#define AE3D_VK_LIGHT_LINEARATTEN 64
#define AE3D_VK_LIGHT_QUADRATICATTEN 68

typedef struct {
    const char *name;
    int offset;
} ae3d_vk_uniform_slot;

static const ae3d_vk_uniform_slot ae3d_vk_uniform_slots[] = {
    { "bloomIntensity", 3824 },
    { "bloomThreshold", 3820 },
    { "bones", 544 },
    { "causticsDepth", 3924 },
    { "causticsIntensity", 3908 },
    { "causticsScale", 3912 },
    { "causticsSpeed", 3916 },
    { "causticsTime", 3928 },
    { "causticsWaterLevel", 3920 },
    { "clearcoatIntensity", 3716 },
    { "clearcoatRoughness", 3712 },
    { "diffuseColor", 3648 },
    { "edgeThreshold", 4072 },
    { "edgeThresholdMin", 4076 },
    { "enableBloom", 3816 },
    { "enableCaustics", 3904 },
    { "enableClearcoat", 3708 },
    { "enableEnergyConservation", 3756 },
    { "enableFoam", 4640 },
    { "enableFog", 3828 },
    { "enableGlobalIllumination", 3804 },
    { "enableImageBasedLighting", 3760 },
    { "enableMultipleScattering", 3752 },
    { "enablePerlinNoise", 3888 },
    { "enableSSAO", 3784 },
    { "enableShadows", 3856 },
    { "enableSheen", 3720 },
    { "enableTransmission", 3744 },
    { "enableVolumetricLighting", 3768 },
    { "enableWaterDistortion", 4696 },
    { "enableWaterNormalMapping", 4704 },
    { "enableWaterReflection", 4684 },
    { "exposure", 3684 },
    { "foamIntensity", 4644 },
    { "fogColor", 3840 },
    { "fogEnd", 3836 },
    { "fogIntensity", 3852 },
    { "fogStart", 3832 },
    { "giBounces", 3812 },
    { "giIntensity", 3808 },
    { "hasNormalMap", 3696 },
    { "hasShadowMap", 3860 },
    { "hasSkyTexture", 4692 },
    { "horizonColor", 4672 },
    { "iblIntensity", 3764 },
    { "invViewProjection", 4096 },
    { "isInstanced", 320 },
    { "isSkinned", 528 },
    { "lightColor", 4608 },
    { "lightCount", 3616 },
    { "lightDirection", 4592 },
    { "lightIntensity", 4620 },
    { "lightPos", 4576 },
    { "lightSpaceMatrix", 464 },
    { "materialAlpha", 3688 },
    { "metallic", 3676 },
    { "model", 336 },
    { "noiseIntensity", 3900 },
    { "noiseOctaves", 3896 },
    { "noiseScale", 3892 },
    { "normalStrength", 3700 },
    { "occlusionStrength", 3704 },
    { "poseBankFrames", 4712 },
    { "projection", 3936 },
    { "reflectivity", 3692 },
    { "roughness", 3680 },
    { "shadowDirection", 3872 },
    { "shadowIntensity", 3864 },
    { "shadowSoftness", 3868 },
    { "shadowTexelWorld", 3884 },
    { "sheenColor", 3728 },
    { "sheenRoughness", 3740 },
    { "skyColor", 4656 },
    { "specularColor", 3664 },
    { "ssaoBias", 3796 },
    { "ssaoIntensity", 3788 },
    { "ssaoRadius", 3792 },
    { "ssaoSampleCount", 3800 },
    { "ssrRoadHeight", 4160 },
    { "ssrStrength", 4164 },
    { "subpixelQuality", 4080 },
    { "texelSize", 4064 },
    { "time", 4168 },
    { "transmissionFactor", 3748 },
    { "useInstanceColor", 324 },
    { "view", 4000 },
    { "viewDistance", 3644 },
    { "viewPos", 3632 },
    { "viewProjection", 400 },
    { "volumetricIntensity", 3772 },
    { "volumetricScattering", 3780 },
    { "volumetricSteps", 3776 },
    { "waterBaseColor", 4624 },
    { "waterDistortionIntensity", 4700 },
    { "waterLevel", 4652 },
    { "waterNormalIntensity", 4708 },
    { "waterOpacity", 4636 },
    { "waterPlaneHeight", 4648 },
    { "waterReflectionIntensity", 4688 },
    { "waveAmplitudes", 4256 },
    { "waveDirections", 4192 },
    { "waveFrequencies", 4320 },
    { "waveHeightMultiplier", 4176 },
    { "wavePhases", 4448 },
    { "waveRandomness", 4180 },
    { "waveSpeedMultiplier", 4172 },
    { "waveSpeeds", 4384 },
    { "waveSteepness", 4512 },
};

#define AE3D_VK_UNIFORM_SLOT_COUNT 108

static inline int ae3d_vk_uniform_offset(const char *name) {
    int low = 0;
    int high = AE3D_VK_UNIFORM_SLOT_COUNT - 1;
    if (!name) return -1;
    while (low <= high) {
        int mid = (low + high) / 2;
        int order = strcmp(name, ae3d_vk_uniform_slots[mid].name);
        if (order == 0) return ae3d_vk_uniform_slots[mid].offset;
        if (order < 0) high = mid - 1; else low = mid + 1;
    }
    return -1;
}

static inline void ae3d_vk_set_float(ae3d_vk_scene *s, int offset, float v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_int(ae3d_vk_scene *s, int offset, int v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_vec3(ae3d_vk_scene *s, int offset, double x, double y, double z) {
    float v[3];
    v[0] = (float)x; v[1] = (float)y; v[2] = (float)z;
    memcpy(s->bytes + offset, v, sizeof(v));
}
static inline void ae3d_vk_set_mat4(ae3d_vk_scene *s, int offset, const double *m) {
    float v[16];
    int i;
    for (i = 0; i < 16; i++) v[i] = (float)m[i];
    memcpy(s->bytes + offset, v, sizeof(v));
}

#endif
