/* Generated by native/shaders/generate.py - do not edit. */
#ifndef AE3D_VK_UNIFORMS_H
#define AE3D_VK_UNIFORMS_H

#include <string.h>

#define AE3D_VK_SCENE_SIZE 448

/* std140 layout, offsets computed from the same declarations the shader
   block is generated from, so the two cannot disagree. */
typedef struct {
    unsigned char bytes[448];
} ae3d_vk_scene;

#define AE3D_VK_OFF_ISINSTANCED 0
#define AE3D_VK_OFF_MODEL 16
#define AE3D_VK_OFF_VIEWPROJECTION 80
#define AE3D_VK_OFF_LIGHT_POSITION 144
#define AE3D_VK_OFF_LIGHT_COLOR 160
#define AE3D_VK_OFF_LIGHT_INTENSITY 172
#define AE3D_VK_OFF_LIGHT_AMBIENTSTRENGTH 176
#define AE3D_VK_OFF_LIGHT_TEMPERATURE 180
#define AE3D_VK_OFF_LIGHT_ISDIRECTIONAL 184
#define AE3D_VK_OFF_LIGHT_DIRECTION 192
#define AE3D_VK_OFF_LIGHT_CONSTANTATTEN 204
#define AE3D_VK_OFF_LIGHT_LINEARATTEN 208
#define AE3D_VK_OFF_LIGHT_QUADRATICATTEN 212
#define AE3D_VK_OFF_VIEWPOS 224
#define AE3D_VK_OFF_DIFFUSECOLOR 240
#define AE3D_VK_OFF_SPECULARCOLOR 256
#define AE3D_VK_OFF_SHININESS 268
#define AE3D_VK_OFF_METALLIC 272
#define AE3D_VK_OFF_ROUGHNESS 276
#define AE3D_VK_OFF_EXPOSURE 280
#define AE3D_VK_OFF_MATERIALALPHA 284
#define AE3D_VK_OFF_ENABLECLEARCOAT 288
#define AE3D_VK_OFF_CLEARCOATROUGHNESS 292
#define AE3D_VK_OFF_CLEARCOATINTENSITY 296
#define AE3D_VK_OFF_ENABLESHEEN 300
#define AE3D_VK_OFF_SHEENCOLOR 304
#define AE3D_VK_OFF_SHEENROUGHNESS 316
#define AE3D_VK_OFF_ENABLETRANSMISSION 320
#define AE3D_VK_OFF_TRANSMISSIONFACTOR 324
#define AE3D_VK_OFF_ENABLEMULTIPLESCATTERING 328
#define AE3D_VK_OFF_ENABLEENERGYCONSERVATION 332
#define AE3D_VK_OFF_ENABLEIMAGEBASEDLIGHTING 336
#define AE3D_VK_OFF_IBLINTENSITY 340
#define AE3D_VK_OFF_ENABLEVOLUMETRICLIGHTING 344
#define AE3D_VK_OFF_VOLUMETRICINTENSITY 348
#define AE3D_VK_OFF_VOLUMETRICSTEPS 352
#define AE3D_VK_OFF_VOLUMETRICSCATTERING 356
#define AE3D_VK_OFF_ENABLESSAO 360
#define AE3D_VK_OFF_SSAOINTENSITY 364
#define AE3D_VK_OFF_SSAORADIUS 368
#define AE3D_VK_OFF_SSAOBIAS 372
#define AE3D_VK_OFF_SSAOSAMPLECOUNT 376
#define AE3D_VK_OFF_ENABLEGLOBALILLUMINATION 380
#define AE3D_VK_OFF_GIINTENSITY 384
#define AE3D_VK_OFF_GIBOUNCES 388
#define AE3D_VK_OFF_ENABLEBLOOM 392
#define AE3D_VK_OFF_BLOOMTHRESHOLD 396
#define AE3D_VK_OFF_BLOOMINTENSITY 400
#define AE3D_VK_OFF_BLOOMRADIUS 404
#define AE3D_VK_OFF_ENABLESHADOWS 408
#define AE3D_VK_OFF_SHADOWINTENSITY 412
#define AE3D_VK_OFF_SHADOWSOFTNESS 416
#define AE3D_VK_OFF_ENABLEPERLINNOISE 420
#define AE3D_VK_OFF_NOISESCALE 424
#define AE3D_VK_OFF_NOISEOCTAVES 428
#define AE3D_VK_OFF_NOISEINTENSITY 432
#define AE3D_VK_OFF_ENABLEHIGHQUALITYFILTERING 436
#define AE3D_VK_OFF_FILTERINGQUALITY 440

static inline void ae3d_vk_set_float(ae3d_vk_scene *s, int offset, float v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_int(ae3d_vk_scene *s, int offset, int v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_vec3(ae3d_vk_scene *s, int offset, double x, double y, double z) {
    float v[3];
    v[0] = (float)x; v[1] = (float)y; v[2] = (float)z;
    memcpy(s->bytes + offset, v, sizeof(v));
}
static inline void ae3d_vk_set_mat4(ae3d_vk_scene *s, int offset, const double *m) {
    float v[16];
    int i;
    for (i = 0; i < 16; i++) v[i] = (float)m[i];
    memcpy(s->bytes + offset, v, sizeof(v));
}

#endif
