#!/usr/bin/env bash
# Compile the Vulkan scene shaders to SPIR-V and embed them in a C header.
#
# The generated header is committed, so building aether3d needs no shader
# compiler; run this only after editing a .vert or .frag here.
#
#   ./native/shaders/build_shaders.sh

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/../ae3d_vk_shaders.h"
GLSLANG="${GLSLANG:-glslangValidator}"

if ! command -v "$GLSLANG" >/dev/null 2>&1; then
    echo "build_shaders: '$GLSLANG' not found (brew install glslang / apt install glslang-tools)" >&2
    exit 1
fi

emit() {
    local stage="$1" symbol="$2" spv
    spv="$(mktemp)"
    "$GLSLANG" -V "$DIR/scene.$stage" -o "$spv" >/dev/null
    printf 'static const unsigned char %s[] = {' "$symbol"
    od -An -v -tu1 "$spv" | tr -s ' ' '\n' | grep -v '^$' | awk '
        { printf (NR % 12 == 1 ? "\n    %s," : " %s,"), $1 }
    '
    printf '\n};\n\n'
    rm -f "$spv"
}

{
    printf '/* Generated by native/shaders/build_shaders.sh — do not edit. */\n'
    printf '#ifndef AE3D_VK_SHADERS_H\n#define AE3D_VK_SHADERS_H\n\n'
    emit vert ae3d_vk_scene_vert_spv
    emit frag ae3d_vk_scene_frag_spv
    printf '#endif\n'
} > "$OUT"

echo "wrote $OUT"
