#!/usr/bin/env python3
"""Generate the Vulkan shaders and their uniform block from the OpenGL sources.

The OpenGL GLSL in src/a3d/shaders/module.ae is the single source of truth. The
Vulkan variants differ only in how uniforms are declared, so they are derived
rather than written twice: a second copy of a seven-hundred-line lighting model
would drift the first time either was touched.

The same declarations produce the std140 uniform block the shader reads and the
C struct the renderer fills, so the two cannot disagree about layout.
"""

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHADERS = ROOT / "src/a3d/shaders/module.ae"
OUT_DIR = Path(__file__).resolve().parent
NATIVE = ROOT / "native"


def block(name):
    text = SHADERS.read_text()
    match = re.search(rf"^const {name} = <<GLSL_END\n(.*?)^GLSL_END$", text, re.S | re.M)
    if not match:
        raise SystemExit(f"generate: {name} not found in {SHADERS}")
    return match.group(1)


SCALARS = {"float": (4, 4), "int": (4, 4), "bool": (4, 4)}
VECTORS = {"vec2": (8, 8), "vec3": (16, 12), "vec4": (16, 16), "mat4": (16, 64)}


def std140(members):
    """Assign std140 offsets, returning (name, type, offset) and the total size."""
    offset = 0
    placed = []
    for kind, name in members:
        align, size = SCALARS.get(kind) or VECTORS[kind]
        offset = (offset + align - 1) // align * align
        placed.append((name, kind, offset))
        offset += size
    return placed, (offset + 15) // 16 * 16


def collect_uniforms(source):
    """Every non-sampler uniform, with the Light struct flattened into it."""
    members = []
    light = re.search(r"uniform struct Light \{(.*?)\} light;", source, re.S)
    if light:
        for kind, name in re.findall(r"\b(vec3|vec4|vec2|float|int|bool)\s+(\w+)\s*;", light.group(1)):
            members.append((kind, f"light_{name}"))
    for kind, name in re.findall(r"^uniform\s+(vec3|vec4|vec2|float|int|bool|mat4)\s+(\w+)\s*;", source, re.M):
        members.append((kind, name))
    return members


def to_vulkan(source, stage, members, samplers, varyings_in, varyings_out):
    """Rewrite an OpenGL shader for Vulkan.

    The uniforms move into an UNNAMED block, so its members keep their original
    names in global scope and every reference in the body still resolves. Naming
    the block would mean rewriting each reference, and the lighting model has
    function parameters that share a uniform's name, so that rewrite cannot be
    done without scope analysis.
    """
    text = source
    text = text.replace("#version 330 core", "#version 450")

    # Light is flattened rather than nested so the C offsets are a plain
    # sequence; `light.x` is a unique pattern, so the rename is safe.
    text = re.sub(r"uniform struct Light \{.*?\} light;", "", text, flags=re.S)
    text = re.sub(r"\blight\.(\w+)", r"light_\1", text)

    text = re.sub(r"^uniform\s+(vec3|vec4|vec2|float|int|bool|mat4)\s+\w+\s*;.*$", "", text, flags=re.M)
    text = re.sub(r"^uniform\s+sampler2D\s+\w+\s*;.*$", "", text, flags=re.M)

    placed, size = std140(members)
    lines = ["layout(std140, set = 0, binding = 0) uniform SceneBlock {"]
    for name, kind, _ in placed:
        lines.append(f"    {kind} {name};")
    lines.append("};")

    for index, sampler in enumerate(samplers):
        lines.append(f"layout(set = 0, binding = {index + 1}) uniform sampler2D {sampler};")

    for index, (kind, name) in enumerate(varyings_out):
        text = re.sub(rf"^out\s+{kind}\s+{name}\s*;.*$",
                      f"layout(location = {index}) out {kind} {name};", text, flags=re.M)
    for index, (kind, name) in enumerate(varyings_in):
        text = re.sub(rf"^in\s+{kind}\s+{name}\s*;.*$",
                      f"layout(location = {index}) in {kind} {name};", text, flags=re.M)

    # The fragment output is the one varying the source leaves unnumbered.
    if stage == "frag":
        text = re.sub(r"^out\s+vec4\s+(\w+)\s*;",
                      r"layout(location = 0) out vec4 \1;", text, flags=re.M)

    text = text.replace("#version 450", "#version 450\n\n" + "\n".join(lines), 1)
    return text, placed, size


def c_struct(placed, size):
    lines = [
        "/* Generated by native/shaders/generate.py - do not edit. */",
        "#ifndef AE3D_VK_UNIFORMS_H",
        "#define AE3D_VK_UNIFORMS_H",
        "",
        "#include <string.h>",
        "",
        f"#define AE3D_VK_SCENE_SIZE {size}",
        "",
        "/* std140 layout, offsets computed from the same declarations the shader",
        "   block is generated from, so the two cannot disagree. */",
        "typedef struct {",
        f"    unsigned char bytes[{size}];",
        "} ae3d_vk_scene;",
        "",
    ]
    for name, kind, offset in placed:
        lines.append(f"#define AE3D_VK_OFF_{name.upper()} {offset}")
    lines += [
        "",
        "static inline void ae3d_vk_set_float(ae3d_vk_scene *s, int offset, float v) {",
        "    memcpy(s->bytes + offset, &v, sizeof(v));",
        "}",
        "static inline void ae3d_vk_set_int(ae3d_vk_scene *s, int offset, int v) {",
        "    memcpy(s->bytes + offset, &v, sizeof(v));",
        "}",
        "static inline void ae3d_vk_set_vec3(ae3d_vk_scene *s, int offset, double x, double y, double z) {",
        "    float v[3];",
        "    v[0] = (float)x; v[1] = (float)y; v[2] = (float)z;",
        "    memcpy(s->bytes + offset, v, sizeof(v));",
        "}",
        "static inline void ae3d_vk_set_mat4(ae3d_vk_scene *s, int offset, const double *m) {",
        "    float v[16];",
        "    int i;",
        "    for (i = 0; i < 16; i++) v[i] = (float)m[i];",
        "    memcpy(s->bytes + offset, v, sizeof(v));",
        "}",
        "",
        "#endif",
    ]
    return "\n".join(lines) + "\n"


def verify_offsets(path, placed):
    """Check the computed std140 offsets against the ones glslang assigns.

    The C side writes at these offsets and the shader reads at glslang's, so a
    disagreement is a silent corruption of every uniform after the first bad
    one. Asking the compiler is cheap; assuming is not.
    """
    result = subprocess.run(["glslangValidator", "-V", "-q", str(path)],
                            capture_output=True, text=True)
    reported = {}
    for line in result.stdout.splitlines():
        match = re.match(r"^(\w+): offset (-?\d+), type \w+, size \d+, index 0,", line)
        if match and int(match.group(2)) >= 0:
            reported[match.group(1)] = int(match.group(2))

    expected = {name: offset for name, _, offset in placed}
    mismatched = [(n, expected[n], reported[n]) for n in reported
                  if n in expected and expected[n] != reported[n]]
    if mismatched:
        for name, ours, theirs in mismatched:
            sys.stderr.write(f"generate: {name} at {ours}, glslang says {theirs}\n")
        raise SystemExit("generate: std140 layout disagrees with the compiler")
    return len(reported)


def aether_offsets(placed, size):
    """The same offsets as an Aether module, so the renderer names uniforms."""
    names = [f"OFF_{name.upper()}" for name, _, _ in placed]
    lines = [
        "// Generated by native/shaders/generate.py - do not edit.",
        "//",
        "// Byte offsets into the scene uniform block, from the same declarations",
        "// that generate the shader's block and the C struct behind it.",
        "",
        "exports (",
    ]
    row = "   "
    for index, name in enumerate(names + ["SCENE_SIZE"]):
        piece = name + ("," if index < len(names) else "")
        if len(row) + len(piece) + 1 > 92:
            lines.append(row)
            row = "   "
        row += " " + piece
    lines.append(row)
    lines.append(")")
    lines.append("")
    for name, _, offset in placed:
        lines.append(f"const OFF_{name.upper()} = {offset}")
    lines.append(f"const SCENE_SIZE = {size}")
    return "\n".join(lines) + "\n"


def spirv(path, stage):
    out = path.with_suffix(path.suffix + ".spv")
    result = subprocess.run(["glslangValidator", "-V", str(path), "-o", str(out)],
                            capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"generate: {path.name} failed to compile")
    return out.read_bytes()


def carray(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for index in range(0, len(data), 12):
        chunk = ", ".join(str(b) for b in data[index:index + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    vertex = block("VERTEX_DEFAULT")
    fragment = block("FRAGMENT_DEFAULT")

    members = collect_uniforms(vertex) + collect_uniforms(fragment)
    seen = {}
    ordered = []
    for kind, name in members:
        if name not in seen:
            seen[name] = kind
            ordered.append((kind, name))

    vertex_out = [("vec2", "fragTexCoord"), ("vec3", "Normal"),
                  ("vec3", "FragPos"), ("vec3", "InstanceColor")]
    vertex_in = [("vec3", "inPosition"), ("vec2", "inTexCoord"), ("vec3", "inNormal")]

    # The vertex inputs already carry explicit locations in the OpenGL source,
    # so they pass through untouched; only the varyings need numbering.
    vk_vertex, placed, size = to_vulkan(vertex, "vert", ordered, [], [], vertex_out)

    vk_fragment, _, _ = to_vulkan(fragment, "frag", ordered, ["textureSampler"],
                                  vertex_out, [])
    vk_fragment = vk_fragment.replace("} scene;", "} scene;\n\nlayout(location = 0) out vec4 FragColor;", 1)

    (OUT_DIR / "scene_vk.vert").write_text(vk_vertex)
    (OUT_DIR / "scene_vk.frag").write_text(vk_fragment)
    (NATIVE / "ae3d_vk_uniforms.h").write_text(c_struct(placed, size))

    module = ROOT / "src/a3d/vkscene"
    module.mkdir(parents=True, exist_ok=True)
    (module / "module.ae").write_text(aether_offsets(placed, size))

    checked = verify_offsets(OUT_DIR / "scene_vk.vert", placed)
    checked += verify_offsets(OUT_DIR / "scene_vk.frag", placed)

    vert_spv = spirv(OUT_DIR / "scene_vk.vert", "vert")
    frag_spv = spirv(OUT_DIR / "scene_vk.frag", "frag")

    header = ["/* Generated by native/shaders/generate.py - do not edit. */",
              "#ifndef AE3D_VK_SCENE_SHADERS_H", "#define AE3D_VK_SCENE_SHADERS_H", "",
              carray("ae3d_vk_scene_vert_spv", vert_spv), "",
              carray("ae3d_vk_scene_frag_spv", frag_spv), "", "#endif"]
    (NATIVE / "ae3d_vk_scene_shaders.h").write_text("\n".join(header) + "\n")

    print(f"generate: {len(ordered)} uniforms, block {size} bytes, "
          f"{checked} offsets verified against glslang, "
          f"vert {len(vert_spv)}B, frag {len(frag_spv)}B")


main()
